/**
 * Application Constants
 * 
 * Centralized constants for the PMIS application
 */

module.exports = {
  // User Roles
  ROLES: {
    ADMIN: 'ADMIN',
    PROJECT_MANAGER: 'PROJECT_MANAGER',
    EQUIPMENT_OFFICER: 'EQUIPMENT_OFFICER',
    FINANCE_CONTROLLER: 'FINANCE_CONTROLLER',
    SUPERVISOR: 'SUPERVISOR',
    VIEWER: 'VIEWER',
  },

  // Project Status
  PROJECT_STATUS: {
    PLANNING: 'PLANNING',
    IN_PROGRESS: 'IN_PROGRESS',
    ON_HOLD: 'ON_HOLD',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
  },

  // Project Types
  PROJECT_TYPES: {
    CONSTRUCTION: 'CONSTRUCTION',
    RENOVATION: 'RENOVATION',
    INFRASTRUCTURE: 'INFRASTRUCTURE',
    EQUIPMENT: 'EQUIPMENT',
    OTHER: 'OTHER',
  },

  // Project Priority
  PROJECT_PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
  },

  // Budget Status
  BUDGET_STATUS: {
    ON_TRACK: 'ON_TRACK',
    AT_RISK: 'AT_RISK',
    EXCEEDED: 'EXCEEDED',
  },

  // Budget Categories
  BUDGET_CATEGORIES: {
    PERSONNEL: 'PERSONNEL',
    EQUIPMENT: 'EQUIPMENT',
    MATERIALS: 'MATERIALS',
    CONTRACTORS: 'CONTRACTORS',
    OTHER: 'OTHER',
  },

  // Equipment Status
  EQUIPMENT_STATUS: {
    AVAILABLE: 'AVAILABLE',
    IN_USE: 'IN_USE',
    MAINTENANCE: 'MAINTENANCE',
    RETIRED: 'RETIRED',
    DAMAGED: 'DAMAGED',
  },

  // Equipment Types
  EQUIPMENT_TYPES: {
    VEHICLE: 'VEHICLE',
    MACHINERY: 'MACHINERY',
    TOOLS: 'TOOLS',
    ELECTRONICS: 'ELECTRONICS',
    FURNITURE: 'FURNITURE',
    OTHER: 'OTHER',
  },

  // Approval Status
  APPROVAL_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    DELEGATED: 'DELEGATED',
  },

  // Milestone Status
  MILESTONE_STATUS: {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    DELAYED: 'DELAYED',
    CANCELLED: 'CANCELLED',
  },

  // Pagination
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },

  // HTTP Status Codes
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
  },

  // Error Codes
  ERROR_CODES: {
    INVALID_INPUT: 'INVALID_INPUT',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  },

  // Cache TTL (in seconds)
  CACHE_TTL: {
    PROJECTS_LIST: 300, // 5 minutes
    PROJECT_DETAIL: 60, // 1 minute
    EQUIPMENT_LIST: 600, // 10 minutes
    USER_PERMISSIONS: 3600, // 1 hour
  },
};
